- .clang-format
- .gitignore
- CMakeLists.txt
- circle.yml
- cmake/Hunter/init.cmake
- lib/CMakeLists.txt
- lib/fizzy/CMakeLists.txt
- lib/fizzy/dummy.cpp
- lib/fizzy/leb128.hpp
- test/CMakeLists.txt
- test/unittests/CMakeLists.txt
- test/unittests/leb128_test.cpp
- CMake project setup
- Unit tests based on GTest (using system installed gtest-dev and FindGTest CMake's standard module).
- Clang-format from evmone
All is up to discussion, but make it quick.
Closes #1.
>  Setup CMake project with unit tests 

- CMakeLists.txt
- circle.yml
- cmake/CableBuildType.cmake
- cmake/CableCompilerSettings.cmake
- cmake/cable.cmake
- codecov.yml
- test/unittests/CMakeLists.txt
- test/unittests/leb128_test.cpp
This adds 2 Cable modules. They were converted to standalone CMake modules so no other Cable files are needed. The modules are also versioned independently. I also added the `cable.cmake` tool that helps with installing / updating Cable modules. E.g. `./cable.cmake install CableBuildType` or `./cable.cmake update`.
This is new way of consuming Cable. All 3 files to be uploaded to the Cable repo.
Code coverage setup is done. ~~Just an admin has to enable codecov.~~
LCOV: https://79-224892340-gh.circle-artifacts.com/0/coverage/index.html
Summary: https://79-224892340-gh.circle-artifacts.com/0/coverage/report.txt
Full: https://79-224892340-gh.circle-artifacts.com/0/coverage/full.html
Missing: https://79-224892340-gh.circle-artifacts.com/0/coverage/missing.html
> cmake: Add Cable modules, configure build type and compilers

- README.md
- lib/fizzy/CMakeLists.txt
- lib/fizzy/types.hpp
- test/unittests/CMakeLists.txt
- test/unittests/parser_test.cpp
Names are based on the Binary Encoding specification
> Add basic Wasm types

- test/unittests/execute_test.cpp
Add case for single end opcode, simplify the local.get/set/tee cases
and reorder tests to match the opcode position.
> Clarify execution unit tests

- lib/fizzy/execute.cpp
- lib/fizzy/parser_expr.cpp
- lib/fizzy/stack.hpp
- test/unittests/CMakeLists.txt
- test/unittests/stack_test.cpp
- Rename `stack` to `Stack` to avoid conflict with `stack` variable defined in `execute()`.
- Change `peek()` argument semantic.
- Add `drop()` method to be used in #25.
> Stack type improvements

- lgtm.yml
Based on https://discuss.lgtm.com/t/update-cmake-to-3-14-to-allow-fetch-content/2048/16
Apparently this works: https://lgtm.com/logs/0940aadb80a435c4499775daaa8a39b7fe87d60e/lang:cpp
> Load CMake 3.15.6 on lgtm

- lib/fizzy/execute.cpp
- test/unittests/execute_control_test.cpp
Requires #25.
When branch is taken, additional stack items must be dropped. I.e. when stack height at the label was `X` branch instruction must make it `X` again (`loop`, `block` with type `[]`) or `X+1` (`block` with type `[t]`).
> Implement stack cleanup in br/br_if instructions

- CMakeLists.txt
And reject compilation if so.
I know this was for a later milestone, but wanted to get this clear.
> Add check into CMake for bigendian platforms

- CMakeLists.txt
- test/unittests/CMakeLists.txt
Docs: https://cmake.org/cmake/help/v3.16/variable/CMAKE_FIND_PACKAGE_PREFER_CONFIG.html
This makes the CONFIG mode of `find_package()` being the first to try if not explicitly specified. Without setting the variable, the MODULE mode is the first to try.
The CONFIG mode should be always preferable in "modern" CMake.
> cmake: Prefer CONFIG mode for find_package

- lib/fizzy/leb128.hpp
- test/unittests/leb128_test.cpp
For types smaller than `int`, there is a promotion to `int` for `~T_unsigned{0}` and the end result is `-1`. It is undefined behavior to shift left a negative value.
> Fix UB in leb128s_decode

- circle.yml
- test/bench/CMakeLists.txt
- Fix fizzy-bench linking with stdc++fs — details explained in comments.
- Run all benchmarks with ASan to detect issues with the tool.
> Check fizzy-bench with ASan

- test/unittests/instantiate_test.cpp
- test/utils/CMakeLists.txt
- test/utils/asserts.hpp
Failure messages look like this:
- Exception thrown, but wrong type
```
[ RUN      ] instantiate.imported_functions_not_enough
/home/andrei/dev/fizzy/test/unittests/instantiate_test.cpp:64: Failure
Failed
Unexpected exception type thrown.
```
- Correct type, wrong message
```
[ RUN      ] instantiate.imported_functions_not_enough
/home/andrei/dev/fizzy/test/unittests/instantiate_test.cpp:64: Failure
Expected equality of these values:
exception.what()
Which is: "Module requires 1 imported functions, 0 provided"
"incorrect message"
```
- Exception not thrown
```
[ RUN      ] instantiate.imported_functions_not_enough
/home/andrei/dev/fizzy/test/unittests/instantiate_test.cpp:68: Failure
Failed
Exception of type std::runtime_error is expected, but none was thrown.
```
> Add macro to test the thrown exception message

- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- test/unittests/execute_test.cpp
- test/unittests/instantiate_test.cpp
Some relevant links
- Import matching described in the spec https://webassembly.github.io/spec/core/exec/modules.html#import-matching
- How instantiating and importing globals looks from the JS side https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Global#Examples
> Implement imported globals passed by pointer

- lib/fizzy/execute.cpp
- test/unittests/instantiate_test.cpp
1. Move data section processing to after globals initialization in `instantiate`.
2. Extract getting the value of constant expression to a separate function `eval_constant_expression`.
3. Use `eval_constant_expression` for both globals inited by globals and data offsets inited by globals. Should be also later used for element section offsets.
> Implement initialization of data section offsets from global constant

- test/unittests/execute_control_test.cpp
This commit was originally a part of #88.
> test: Extend execute_control.nested_blocks test

- cmake/CableCompilerSettings.cmake
Do not explicitly set `-mtune=generic`, this is default anyway.
The GCC documentation is lacking this information, but I checked `libfizzy.a`.
The article about this subject: https://lemire.me/blog/2018/07/25/it-is-more-complicated-than-i-thought-mtune-march-in-gcc/.
> CableCompilerSettings 1.0.1

- lib/fizzy/execute.cpp
- test/unittests/instantiate_test.cpp
This is required by the instantiation algorithm in the spec https://webassembly.github.io/spec/core/exec/modules.html#instantiation
> Make instantiation fail in case element or data section doesn't fit table or memory

- circle.yml
This uses virtual machine based executor (Ubuntu 16.04) and takes binaries from linux release build.
Using virtual machine gives more stable results comparing to docker jobs.
> ci: Add benchmark job

- test/CMakeLists.txt
- test/bench/CMakeLists.txt
- test/spectests/CMakeLists.txt
- test/spectests/spectests.cpp
Part of #110
Commands that can be used to convert all *.wast files in current dir to json/wasm files in separate subdirs:
```
mkdir json
for f in *.wast; do mkdir json/${f%.*}; wast2json $f -o json/${f%.*}/${f%.*}.json; done
```
> Add spectest runner tool

- lib/fizzy/execute.cpp
- test/unittests/execute_numeric_test.cpp
I guess this case is not mentioned in the spec, because unlike for `div_s` which traps, `rem_s` should return a valid result for this case (0), so there's nothing special to mention.
It's just an implementation detail that `%` is not working for these inputs.
> Fix rem_s instructions causing SIGFPE

- circle.yml
- test/unittests/execute_control_test.cpp
- wat2wasm4cpp.py
1. Script is written in Python. Can be done in CMake someday, but this requires substantially  more work.
2. It takes a C++ source file as an argument.
3. It searches for `/* wasm ... */` comments containing WAT code. I think a match like `/*\n(... */` would also work. We can discuss if there should be a common name for this variable, e.g. `bin`, `wasm`, `wasm_binary`.
4. The result wasm binary is used to update the `const auto <any_name> = from_hex("...");`. This was used as a start because it was like that in the file already. There is some issue with formatting `""_bytes"` automatically. If this pattern is not found, the result wasm is ignored.
5. It expects `wat2wasm` (wabt) in the PATH.
6. The modified source file could be additionally formatted with clang-format, but this is not …
> Script wat2wasm4cpp

- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- test/unittests/end_to_end_test.cpp
- test/unittests/execute_test.cpp
- test/unittests/instantiate_test.cpp
- test/utils/fizzy_engine.cpp
Some relevant links
- Matching memory imports described in spec https://webassembly.github.io/spec/core/exec/modules.html#memories
https://webassembly.github.io/spec/core/exec/modules.html#limits
-  how memory importing looks from the JS side https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory#Examples
- more about memories from JS point of view (note the last paragraph about imported memory usage) https://webassembly.org/getting-started/js-api/#memory
> Implement imported memory

- lib/fizzy/parser_expr.cpp
- test/unittests/parser_test.cpp
Fixes these tests in `memory.wast`
```
Line 11: module Instantiating memory.6.wasm PASSED
Line 12: assert_return FAILED Function trapped.
Line 13: module Instantiating memory.7.wasm PASSED
Line 14: assert_return FAILED Function trapped.
Line 15: module Instantiating memory.8.wasm PASSED
Line 16: assert_return FAILED Function trapped.
```
> Fix parsing memory_size and memory_grow instructions

- lib/fizzy/parser.cpp
- lib/fizzy/parser.hpp
- lib/fizzy/parser_expr.cpp
- test/unittests/parser_test.cpp
This is a proposal to change template struct specializations to template function specializations.
1. The types that are uses as vector element require template specialization of `parse()`.
2. All other types are implemented as `parse_xxx()`. Including `parse_vec`.
This is only a syntactic change.
> Parser rework

- test/unittests/parser_test.cpp
This replaces the unit test for `Locals` with a one using full wasm module. This removes the need of exposing `parse<Locals>()` function in `fizzy` library.
> test: Replace parser locals tests with full wasm modules

- lib/fizzy/leb128.hpp
- test/unittests/leb128_test.cpp
This fixes these tests in `int_literals.wast`
```
Line 40: assert_return FAILED Incorrect returned value. Expected: 18446744071562067969 (0xffffffff80000001) Actual: 18446744073709551609 (0xfffffffffffffff9)
Line 41: assert_return FAILED Incorrect returned value. Expected: 18446744071562067968 (0xffffffff80000000) Actual: 18446744073709551608 (0xfffffffffffffff8)
Line 42: assert_return FAILED Incorrect returned value. Expected: 18446744071562067968 (0xffffffff80000000) Actual: 18446744073709551608 (0xfffffffffffffff8)
Line 43: assert_return FAILED Incorrect returned value. Expected: 18446744071562067969 (0xffffffff80000001) Actual: 18446744073709551609 (0xfffffffffffffff9)
```
```
Line 52: assert_return FAILED Incorrect returned value. Expected: 9223372036854775809 (0x8000000000000001) …
```
> Fix sign extension in signed LEB128 decoder

- lib/fizzy/execute.cpp
- test/unittests/instantiate_test.cpp
- test/utils/fizzy_engine.cpp
- test/utils/wabt_engine.cpp
- test/utils/wasm3_engine.cpp
Module is allowed to not have any memory (then all memory instructions are invalid)
https://github.com/WebAssembly/spec/blob/3b2489d7e570ca0f8d32e9d0b1a1e8255c4212b7/test/core/memory.wast#L22-L25
> Don't allocate empty memory when none is defined or imported

- lib/fizzy/leb128.hpp
- lib/fizzy/parser.cpp
- lib/fizzy/parser.hpp
- lib/fizzy/parser_expr.cpp
- test/unittests/leb128_test.cpp
- test/unittests/parser_test.cpp
This adds input buffer bounds checking in wasm binary parser, except for `parse_expr` which parses instructions (to be done later).
> Parser bounds checking

- circle.yml
- cmake/Hunter/init.cmake
Because we accidentally discovered issue with usage of libbenchmark let the Debug build use Debug Hunter deps officially. This is going to be tested by clang-latest-asan.
> cmake: Build Debug Hunter debs for Debug build type 

- lib/fizzy/parser.cpp
- test/unittests/parser_test.cpp
> Parse names of custom sections (as required by the spec)

- lib/fizzy/parser.cpp
- test/unittests/parser_test.cpp
Do not allow a custom section which name length exceeds the total size of the section.
> Fix custom section name parsing

- lib/fizzy/parser_expr.cpp
Requires #158, #163.
```
Comparing bin/fizzy-bench-master to bin/fizzy-bench
Benchmark                                          Time             CPU      Time Old      Time New       CPU Old       CPU New
-------------------------------------------------------------------------------------------------------------------------------
fizzy/parse/blake2b                             -0.2990         -0.2990         14528         10183         14528         10183
fizzy/parse/blake2b                             -0.3017         -0.3017         14533         10148         14533         10148
fizzy/parse/blake2b                             -0.3015         -0.3015         14520         10143         14520         10143
fizzy/parse/blake2b                             -0.3001         -0.3002 …
```
> Optimize push() helper in parse_expr()

- lib/fizzy/parser.cpp
On my computer it gives 15-7-0.5% speed up on the benchmarks as it highly depends on input. No measurable speed increase if there's no data section or substantial number of strings (exports/imports/custom sections).
> Optimise parse_string and parse<Data>

- circle.yml
- lib/fizzy/execute.cpp
- test/unittests/execute_numeric_test.cpp
If the binary_op() operates on i32 values, we want to zero-extend the final value to i64 so avoid int32_t -> uint64_t conversion which is the sign-extend one.
> Fix i32.{shr, div, rem}_s instructions

- lib/fizzy/leb128.hpp
- test/unittests/leb128_test.cpp
This adds the handling of the unused bits according to this note in the spec:
https://webassembly.github.io/spec/core/binary/values.html#integers
All of the `binary-leb128.wast` spectests pass with this fix.
> Fix handling of unused bits in LEB128 decoder

- circle.yml
- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- test/unittests/api_test.cpp
Alternative to https://github.com/wasmx/fizzy/pull/181
Adds APIs for finding exported functions/globals/tables/memories in the form of `ExternalFunction`/`ExternalGlobal`/`ExternalTable`/`ExternalMemory` instances ready to be imported into another module.
~~The same should be done for functions, but this requires https://github.com/wasmx/fizzy/pull/171~~ Done.
Using this in spectests will look like this:
https://github.com/wasmx/fizzy/blob/b287cc004c3de064b469ed6e99f2ca262dd6dd92/test/spectests/spectests.cpp#L365-L410
> Add APIs to find exports

- test/spectests/spectests.cpp
1. Implements `register` command, which saves the name of the module to be used in imports.
2. ~~Adds support for modules importing functions (other imports not supported yet)~~ 
Included in https://github.com/wasmx/fizzy/pull/182
3. ~~(requires https://github.com/wasmx/fizzy/pull/170) Adds the `spectest` module, available for all test files.~~
Moved to https://github.com/wasmx/fizzy/pull/215
> spectest: support "register" command

- lib/fizzy/parser.hpp
- test/bench_internal/CMakeLists.txt
- test/bench_internal/experimental.cpp
- test/bench_internal/parser_benchmarks.cpp
- test/unittests/parser_test.cpp
- test/utils/CMakeLists.txt
- test/utils/leb128_encode.cpp
- test/utils/leb128_encode.hpp
Do not reserve memory for `size` number of elements. It can be a lie causing huge allocation without actual elements to follow.
> parser: Do not reserve memory for vec elements

- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- test/unittests/api_test.cpp
- test/unittests/execute_call_test.cpp
- test/unittests/instantiate_test.cpp
From `call_indirect` [execution spec](https://webassembly.github.io/spec/core/exec/instructions.html#exec-call-indirect):
Spec test for this: https://github.com/WebAssembly/spec/blob/e3a3c12f51221daaa901691e674d7ff990029122/test/core/elem.wast#L353
This PR changes table's internal representation to `std::vector<std::optional<FuncIdx>>`.
It would be possible to represent it with `std::vector<std::function<execution_result(std::vector<uint64_t>)>>`, but `call_indirect` also checks the type of the called function against opcode's immediate, so we would need to store addditionally table function types or function indices. Vector of optionals seems at least simpler for now.
> Trap when call_indirect chooses uninitialized table element

- lib/fizzy/leb128.hpp
```
Comparing bin/fizzy-bench-master to bin/fizzy-bench
Benchmark                                   Time             CPU      Time Old      Time New       CPU Old       CPU New
------------------------------------------------------------------------------------------------------------------------
fizzy/parse/blake2b                      -0.0870         -0.0873         10146          9263         10146          9260
fizzy/parse/memset                       -0.0730         -0.0732          2876          2666          2876          2665
fizzy/parse/mul256_opt0                  -0.1041         -0.1044          3330          2983          3330          2982
fizzy/parse/sha1                         -0.0664         -0.0680         14003         13073         14003         13050 …
```
> Make LEB128 decoding procedures inline

- test/bench/bench.cpp
- test/unittests/wasm_engine_test.cpp
- test/utils/fizzy_engine.cpp
- test/utils/wabt_engine.cpp
- test/utils/wasm3_engine.cpp
- test/utils/wasm_engine.hpp
We now recreate full instance for each run. This is safer and matches the normal usage. This also needs a simplified WasmEngine interface.
Timer is paused during instantiation but pause/resume functions are supposed to be quite heavy.
The timings are quite disturbed.
```
Comparing bin/fizzy-bench-master to bin/fizzy-bench
Benchmark                                          Time             CPU      Time Old      Time New       CPU Old       CPU New
-------------------------------------------------------------------------------------------------------------------------------
fizzy/execute/blake2b/rounds_1                  -0.0487         -0.0308        166130        158040        163046        158026
wabt/execute/blake2b/rounds_1                  -0.0564         -0.0371        175538 …
```
> Rework "execute" benchmark

- CMakeLists.txt
- circle.yml
- lib/fizzy/parser.cpp
- test/CMakeLists.txt
- test/fuzzer/CMakeLists.txt
- test/fuzzer/parser_fuzzer.cpp
Build with `-DFIZZY_TESTING=ON -DFIZZY_FUZZING=ON`.
Clang compiler is required to build this.
```
bin/fizzy-fuzz-parser corpus
```
```
bin/fizzy-fuzz-parser -help=1
```
> Parser fuzzer

- circle.yml
- lib/fizzy/execute.cpp
- lib/fizzy/parser.cpp
- test/unittests/execute_numeric_test.cpp
- test/unittests/execute_test.cpp
- test/unittests/parser_test.cpp
> parser: Ensure there is a matching function section for each code section

- lib/fizzy/parser.cpp
- lib/fizzy/types.hpp
- test/unittests/parser_test.cpp
When parsing code section (vec of codes), only record the wasm binary section containing the code (based on the code size available). The code are fully processed later, after information about all sections is collected. This decouples code parsing from parse_vec() and is preparation for passing additional information to the code parsing procedure.
> parser: Process code separately from code section

- lib/fizzy/exceptions.hpp
- lib/fizzy/parser.cpp
- lib/fizzy/parser.hpp
- lib/fizzy/parser_expr.cpp
- test/unittests/execute_test.cpp
- test/unittests/parser_expr_test.cpp
- test/unittests/parser_test.cpp
Requires: #238.
Issue: when there is no memory defined in a module any memory access instruction (store, load) causes a crash.
I noticed that wabt rejects such module on parsing. We should confirm it is valid solution because it is a nice one (no additional check is needed during execution).
> validation: Reject modules with memory instructions but without memory

- CMakeLists.txt
- circle.yml
- lib/fizzy/execute.cpp
This makes CI to fail on UBSan warnings (previously silently ignored). And fixes issues we accumulated over time.
Requires #229, #225.
> ci: Enable UBSan errors

- circle.yml
- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- test/unittests/api_test.cpp
- test/unittests/execute_call_test.cpp
- test/unittests/execute_control_test.cpp
- test/unittests/execute_test.cpp
- test/unittests/instantiate_test.cpp
1. Make `ExternalFunction` a struct containing `std::function` and `FuncType`.
2. In `match_imported_functions` check imported function types against import types declared in the module.
3. Refactor to get rid of `Instance::imported_function_types`, because this info is now included in `Instance::imported_functions`
This fixes failures in `imports.wast`
> Check imported function type

- lib/fizzy/parser_expr.cpp
- test/unittests/parser_expr_test.cpp
Cleanups and refactoring to control stack as preliminary work for #244.
1. Use `std::stack` instead of `Stack` to help with #247 where `Stack` is replaced and is not generic any more.
2. Renames to match Wasm Validation Algorithm https://webassembly.github.io/spec/core/appendix/algorithm.html.
3. Add the implicit function's block to control stack. This guarantees that there is always a control frame.
> parser: Control stack refactor

- test/unittests/wasm_engine_test.cpp
This can be enabled after #258.
> tests: enable case for wabt in wasm_engine_test

- circle.yml
- lib/fizzy/execute.cpp
- test/unittests/instantiate_test.cpp
[Instantiation algorithm](https://webassembly.github.io/spec/core/exec/modules.html#instantiation) in the spec has separate steps for checking the bounds, preceding the steps for filling table/memory:
[...]
[...]
This resolves some failures in `linking.wast`
> Check element and data section bounds before modifying imported table and memory

- circle.yml
- lib/fizzy/execute.cpp
- lib/fizzy/parser.cpp
- test/unittests/instantiate_test.cpp
- test/unittests/parser_test.cpp
- test/unittests/validation_test.cpp
- test/utils/wasm_binary.hpp
1. Throw `validation_error` instead of `parser_error` in table/memory number checks.
2. Move related tests to validation_test.cpp
3. assert in `instantiate` for the same checks instead of throwing `instantiate_error`
3.1 remove related cases from instantiation tests
3.1 is required for converting instantiation tests to wat2wasm https://github.com/wasmx/fizzy/blob/a534d42636da97700db634e2640b8947f44a4735/test/unittests/instantiate_test.cpp#L172-L184
> validation: table and memory number

- test/unittests/execute_call_test.cpp
A regression test for incorrect number of arguments passed to a call.
> test: Add "call_nonempty_stack" test

- circle.yml
- lib/fizzy/execute.cpp
- lib/fizzy/parser.cpp
- lib/fizzy/types.hpp
- test/unittests/parser_test.cpp
- test/unittests/validation_test.cpp
Also add validation of imported function type index.
Required for #267
> refactor: move the loop splitting imports from instantiate to parser

- circle.yml
- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- test/unittests/api_test.cpp
- test/unittests/execute_call_test.cpp
- test/unittests/execute_control_test.cpp
- test/unittests/execute_test.cpp
- test/unittests/instantiate_test.cpp
This fixes remaining failures in `elem.wast` and `linking.wast`. 
There are two scenarios:
1.
- module A has exported table
- module A adds via element section some of its functions into the table.
- module B imports this table
- `call_indirect` executed with this table in the instance of B will call a function in A.
Unit test demonstrating it: https://github.com/wasmx/fizzy/blob/0a51bc1ec4db349249113ed99a0c8371c1368c65/test/unittests/execute_call_test.cpp#L353
2. 
- module A has exported table
- module B imports this table and adds via element section some of its functions into this shared table.
- module B's start function traps, so it can't be instantiated.
- After this the change to shared table can't be rolled back, and so the table still must contain the functions of module B. They …
> call_indirect for functions from another modules

- test/unittests/execute_call_test.cpp
- test/unittests/instantiate_test.cpp
Just a curious case of two modules recursing infinitely into one another via shared table.
(doesn't exist in spec tests)
> test: two modules calling each other with call_indirect

- test/ci-benchmark.sh
My shell (fish) requires shebang to be the first bytes in the file.
Fixes #280.
> ci: fix shebang in ci-benchmark.sh

- test/benchmarks/ecpairing.inputs
> benchmarks: Remove execute/ecparing/empty

- lib/fizzy/CMakeLists.txt
- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- lib/fizzy/module.hpp
- lib/fizzy/parser.hpp
- lib/fizzy/types.hpp
Needed for https://github.com/wasmx/fizzy/pull/267
> refactor: move Module and function_type helper to module.hpp

- lib/fizzy/module.hpp
- lib/fizzy/parser.cpp
- lib/fizzy/parser.hpp
- lib/fizzy/parser_expr.cpp
- test/unittests/parser_expr_test.cpp
And add has_memory() helper on Module
Pulled out of #267. Needed for a lot of validation steps.
> refactor: pass Module to parse_expr

- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- lib/fizzy/types.hpp
- test/unittests/api_test.cpp
- test/unittests/instantiate_test.cpp
Imported table and memory are allowed to have narrower limits than the ones defined in the module. If it is then reexported, the limits must be original (narrower) ones, otherwise it might not fit as an import to another module. The disabled tests demonstrate it https://github.com/wasmx/fizzy/blob/7dabb5255a2f1b9fe7fb253a617851184951e696/test/unittests/api_test.cpp#L278
PR adds new members to `Instance` to save the limits of either local or imported table/memory. These limits are then returned from `find_exported_table`/`find_exported_memory`.
I also tried to use `std::variant` to refactor table in https://github.com/wasmx/fizzy/pull/302 but the approach in this PR seems now much simpler.
> Fix disabled tests around reexports of imported table/memory

- test/utils/asserts.cpp
It was outputting `(ab, )` instead of `(a, b)`
> test: fix execution_result printer

- lib/fizzy/execute.cpp
No issue in clang-tidy-10 any more.
> Drop a clang analyzer warning suppression

- circle.yml
- lib/fizzy/parser_expr.cpp
- test/unittests/parser_expr_test.cpp
- test/unittests/validation_stack_test.cpp
This validates if frames leave enough results they promised, however this check is missing for function frames (function type information is missing, but this is fixed in #312 - see a TODO comment). The situation where there is more results left is also not reported, but is easy to add - see TODO comment. This cannot be applied now because a lot of false positives when function result arity is so far assumed 0.
The frame `stack_height` now uses absolute values what will be useful for jump resolving in #312 and makes computing code's max stack height straight forward (as it is max value of any `frame.stack_height`).
> More stack height validation

- circle.yml
This is valuable because this tests usage of `libc++` standard library.
> ci: Run sanitizers job on macos / ugrade to XCode 11.5.0

- lib/fizzy/parser.cpp
- test/unittests/parser_expr_test.cpp
- test/unittests/parser_test.cpp
The validation of type indices in function section must be fully
finished before processing any code. This is because there may be a call
in code[i] referencing function[i + n].
> Fix function section validation

- test/unittests/wasm_engine_test.cpp
> test: also test instantiate with parser errors in wasm_engine_test

- lib/fizzy/parser_expr.cpp
- test/unittests/validation_stack_test.cpp
After a change to use absolute values for frame.stack_height the stack
height requirements for call were incorrectly checked. This fixes it.
> Fix stack height validation for calls

- lib/fizzy/execute.cpp
- lib/fizzy/parser_expr.cpp
- lib/fizzy/stack.hpp
- lib/fizzy/types.hpp
- test/unittests/execute_call_test.cpp
- test/unittests/execute_numeric_test.cpp
- test/unittests/parser_expr_test.cpp
- test/unittests/stack_test.cpp
- test/unittests/validation_stack_test.cpp
Execution comparison
```
Comparing master-exec to opt-exec                                                                                                                                       
Benchmark                                                            Time             CPU      Time Old      Time New       CPU Old       CPU New                       
-------------------------------------------------------------------------------------------------------------------------------------------------
fizzy/execute/blake2b/512_bytes_rounds_1_mean                     -0.1219         -0.1218            98            86            98            86
fizzy/execute/blake2b/512_bytes_rounds_16_mean                    -0.1459         -0.1459          1472          1257          1472 …
```
> Stack optimization

- circle.yml
- lib/fizzy/parser.cpp
- lib/fizzy/parser.hpp
- lib/fizzy/parser_expr.cpp
- test/unittests/parser_expr_test.cpp
Required for #312 
Resolves one TODO in `parse_expr` and 45 validation spec tests (must be the tests checking if function stack has enough results at the end of execution)
> validation: use correct function arity in stack height validation

- lib/fizzy/parser_expr.cpp
- lib/fizzy/stack.hpp
- test/unittests/stack_test.cpp
> refactor: use Stack class for control stack in parser

- cmake/wasm3_03_startfunc.patch
Includes https://github.com/wasm3/wasm3/pull/145 in our patchset.
The main benefit is we don't get hundreds of lines of `Result: <Empty Stack>` displayed by fizzy-bench.
We have a test case for this, `wasm_engine/start_func`, which seems to work.
> wasm3: add patch for better start function support

- test/unittests/execute_control_test.cpp
- test/unittests/parser_expr_test.cpp
- test/unittests/parser_test.cpp
- test/unittests/validation_stack_test.cpp
In preparation to enable "too many results" validation check, this converts some existing wasm test case to valid ones in terms of stack height.
> test: Make some tests valid

- lib/fizzy/execute.cpp
- lib/fizzy/parser_expr.cpp
- test/unittests/execute_control_test.cpp
- test/unittests/parser_expr_test.cpp
Replaces #297 
I tried to make the change history to gradually introduce resolving in parser, at first keeping control stack in execute and old instruction immediates, then deleting it in the very end. So this can be reviewed by commit.
For `br_table` it currently puts arity into immedaites for each label. This should be further optimized to have one arity immediate for entire `br_table` instruction.
> Resolve br/br_if/br_table in parser

- lib/fizzy/execute.cpp
- lib/fizzy/types.hpp
- test/unittests/CMakeLists.txt
- test/unittests/types_test.cpp
As requested by @gumb0 in #331.
> refactor: move FuncType comparisons operators to types.hpp

- lib/fizzy/parser_expr.cpp
> refactor: use proper variable names instead of generic imm in parser_expr

- lib/fizzy/stack.hpp
- test/unittests/execute_test.cpp
Requires #247 
This implements "small vector" / "small string" optimization to `OperandStack`. When the max stack height is smaller than static limit we omit dynamic allocation and use static storage within `OperandStack`.
The max stack height is usually very small. E.g. for LLVM generated code it is usually 3 except calls (as they naturally requires the stack to have all call args).
```
fizzy/execute/blake2b/rounds_1_mean                      -0.1445         -0.1445        265267        226946        265240        226922
fizzy/execute/blake2b/rounds_16_mean                     -0.1447         -0.1447       3975578       3400162       3975531       3400087
fizzy/execute/ecpairing/multipoint_mean                  -0.1318         -0.1318    2871590597    2493111309    2871538432 …
```
> Small stack optimization

- lib/fizzy/execute.cpp
It's pushed to immediates as `uint32_t`, and should be read with the same type. https://github.com/wasmx/fizzy/blob/5db0431404c7c35d58e5288626b931b182c500ac/lib/fizzy/parser_expr.cpp#L128
> Fix reading  parent stack height from branch instructions immediates

- circle.yml
- lib/fizzy/parser_expr.cpp
- test/unittests/execute_control_test.cpp
- test/unittests/validation_test.cpp
Required for #354.
There's a slight complication around loop's arity: turns out if there's loop in `br_table` labels, it's arity is considered always 0 (and then `br_table` is valid only if all labels have arity 0). 
It's difficult to find clear confirmation of this in the spec, but spec tests cover it in this case https://github.com/WebAssembly/spec/blob/636b862b9c8a25ad65fb240fefd673e7f23bcdd0/test/core/br_table.wast#L1229-L1244
> Validate arity of labels in br_table

- lib/fizzy/leb128.hpp
- lib/fizzy/parser.hpp
- lib/fizzy/utf8.cpp
- lib/fizzy/utf8.hpp
Instead of a mix of input/start/pos.
Inspired by #361.
> Use pos/end consisently in the parser

- circle.yml
- lib/fizzy/parser_expr.cpp
- test/unittests/validation_stack_test.cpp
> Enable "too many results" stack height validation

- circle.yml
- lib/fizzy/parser_expr.cpp
- test/unittests/validation_stack_test.cpp
This applies the logic of [Validation algorithm](https://webassembly.github.io/spec/core/appendix/algorithm.html) regarding unreachable to stack height checks.
Specifically
- After unreachable any underflowing pop is ignored, but pushes add to stack growth.
- When current frame is marked unreachable, stack height is reset.
"Simplify" commit is not squashed yet to show the different nested organization of nested ifs. I find the final one better.
> Validate stack height after unreachable

- lib/fizzy/parser_expr.cpp
- test/unittests/validation_stack_test.cpp
The change suggested in https://github.com/wasmx/fizzy/pull/384#discussion_r438697161
> refactor: Unify stack height handling for instructions and calls in parser

- test/bench/bench.cpp
Most of the benchmark cases don't have init memory at all - this is handled by a separate benchmark loop where `init_memory()` is not used at all.
For the remaining cases (mul256, eli_interpreter) the init memory is very small (max 105 bytes for an eli_interpreter input). It is not worth to pause and resume the timer as 
> PauseTiming()/ResumeTiming() are relatively heavyweight, and so their use should generally be avoided within each benchmark iteration, if possible.
```
fizzy/execute/blake2b/512_bytes_rounds_1_mean                     -0.0212         -0.0213            92            90            92            90
fizzy/execute/blake2b/512_bytes_rounds_16_mean                    -0.0179         -0.0179          1378          1354          1378          1354 …
```
> bench: Don't pause/resume timer

- test/unittests/execute_control_test.cpp
Idea taken from https://github.com/wasmx/fizzy/pull/367#issuecomment-637744483.
This seems to be running slightly slower, so leaving only tests case.
Diff for reference:
```diff
--- a/lib/fizzy/execute.cpp
+++ b/lib/fizzy/execute.cpp
@@ -678,20 +678,19 @@ execution_result execute(
goto end;
break;
}
-        case Instr::br:
+
case Instr::br_if:
-        case Instr::return_:
-        {
-            // Check condition for br_if.
-            if (instruction == Instr::br_if && static_cast<uint32_t>(stack.pop()) == 0)
+            if (static_cast<uint32_t>(stack.pop()) == 0)
{
immediates += BranchImmediateSize;
break;
}
-
+            [[fallthrough]];
+        case Instr::br:
+        case Instr::return_:
branch(code, stack, pc, immediates);
break;
-        }
+
case Instr::br_table:
{
const …
```
> test: Add one more br_if test case 

- lib/fizzy/execute.cpp
- lib/fizzy/module.hpp
- lib/fizzy/parser.cpp
- lib/fizzy/types.hpp
- test/unittests/instantiate_test.cpp
- test/unittests/parser_test.cpp
Required for type validation, pulled out from #385
> parser: Save global value type during parsing

- lib/fizzy/execute.cpp
- lib/fizzy/parser_expr.cpp
- lib/fizzy/stack.hpp
- test/unittests/parser_expr_test.cpp
Instead of keeping information about the absolute height to rewind the
stack to, keep the number of stack items to drop (without the number of
results - arity of the result type).
This makes OperandStack simpler (no need to track the bottom of the stack). No speed change.
> Keep number of stack items to drop for branches

- circle.yml
- lib/fizzy/execute.cpp
- lib/fizzy/parser.cpp
- test/unittests/instantiate_test.cpp
- test/unittests/parser_test.cpp
- test/unittests/validation_test.cpp
First part of https://github.com/wasmx/fizzy/pull/372
> Validate constant expressions in globals initializers

- lib/fizzy/parser.cpp
- test/unittests/instantiate_test.cpp
- test/unittests/parser_test.cpp
- test/unittests/validation_test.cpp
Second part of https://github.com/wasmx/fizzy/pull/372
> Validate constant expressions for data offset initialization

- lib/fizzy/execute.cpp
- lib/fizzy/parser.cpp
- test/unittests/instantiate_test.cpp
- test/unittests/parser_test.cpp
- test/unittests/validation_test.cpp
Third part of https://github.com/wasmx/fizzy/pull/372
> Validate constant expressions for elem offset initialization

- circle.yml
- lib/fizzy/parser.cpp
- test/unittests/parser_test.cpp
- test/unittests/validation_test.cpp
~~Based on #372~~
Based on #397
According to [validation spec](https://webassembly.github.io/spec/core/valid/modules.html#globals), result of constant expression has type
- `[t]` for global initializer
- `[i32]` for offset initializers
This implies that constant expression can have only single `*.const` or `global.get` instruction.
Spec tests check that with expected error "type mismatch": https://github.com/WebAssembly/spec/blob/60facfbb74cbb9f818258bbb07d02c581352e592/test/core/global.wast#L281-L289
> Validate number of instructions in constant expression

- CHANGELOG.md
I didn't include some very minor PRs like variable renaming etc.
Also didn't include #389 and #390 which will be needed only for type validation.
> changelog: add 0.2.0 details

- .clang-format
- .clang-tidy
- lib/fizzy/CMakeLists.txt
- lib/fizzy/span.hpp
- test/unittests/CMakeLists.txt
- test/unittests/span_test.cpp
Implements some parts of `std::span<>` from C++20.
Taken from #359 and extended for needs in #403.
> Span utility

- circle.yml
- lib/fizzy/module.hpp
- lib/fizzy/parser.cpp
- lib/fizzy/parser_expr.cpp
- test/unittests/CMakeLists.txt
- test/unittests/module_test.cpp
> Add module helper for finding global type

- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- test/unittests/end_to_end_test.cpp
- test/unittests/execute_call_test.cpp
- test/unittests/execute_control_test.cpp
- test/unittests/execute_numeric_test.cpp
- test/unittests/execute_test.cpp
- test/utils/CMakeLists.txt
- test/utils/execute_helpers.hpp
This an overload of execute that takes a module and instantiate it internally. This is convenient for unit tests but rather not desirable in "public" headers. So it is moved to testutils.
> Move execute(Module, ...) to execute_helpers.hpp (testutils)

- lib/fizzy/CMakeLists.txt
- lib/fizzy/constexpr_vector.hpp
- test/unittests/CMakeLists.txt
- test/unittests/constexpr_vector_test.cpp
> Add constexpr_vector class

- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- lib/fizzy/span.hpp
- test/bench_internal/CMakeLists.txt
- test/bench_internal/execute_benchmarks.cpp
- test/spectests/spectests.cpp
- test/unittests/api_test.cpp
- test/unittests/execute_call_test.cpp
- test/unittests/execute_control_test.cpp
- test/unittests/execute_test.cpp
- test/unittests/instantiate_test.cpp
- test/unittests/span_test.cpp
- test/utils/execute_helpers.hpp
- test/utils/fizzy_engine.cpp
This passes function arguments by reference (instead of by value with `std::vector`). This eliminates one allocation per call because - previously one allocation was done to create the vector, then another to create locals.
Changing `std::vector` to `const std::vector&` may have been enough, but `span` is more generic and easier to refactor with.
The `snap` does not have unit tests as it is trivial and not all methods are currently used after full transition.
```
fizzy/execute/blake2b/512_bytes_rounds_1_mean                     -0.0834         -0.0835            85            78            85            78
fizzy/execute/blake2b/512_bytes_rounds_16_mean                    -0.0758         -0.0758          1262          1166          1262          1166
fizzy/execute/ecpairing/onepoint_mean …
```
> Pass function args by reference using span<>

- circle.yml
This creates coverage report (same as for unittests) out of spectests execution. It is available as CircleCI artifact.
The codecov report can be split into two parts, but I'm leaving that for other time.
Closes #406
> Spectests code coverage

- .clang-format
Use deprecated "Standard: Cpp11" meaning "Latest" to lower requirements
of the clang-format tool version.
> clang-format: Use Cpp11 to lower requirements

- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- test/spectests/spectests.cpp
- test/unittests/api_test.cpp
- test/unittests/execute_call_test.cpp
- test/unittests/execute_control_test.cpp
- test/unittests/execute_test.cpp
- test/unittests/instantiate_test.cpp
- test/utils/asserts.cpp
- test/utils/asserts.hpp
- test/utils/fizzy_engine.cpp
This re-implements the execution_result struct. Now it has three valid
states: value, void and trap. The struct is simplified, close to POD
type, std::vector is not used any more.
In benchmarks for certain cases (such as ecpairing) deleting an `std::vector` took quite a big chunk of time. I thought perhaps the moved stack for the return value could be the culprit, hence did this change. However my local benchmarks are inconclusive.
> New version of execution_result

- circle.yml
- lib/fizzy/parser_expr.cpp
- test/unittests/validation_stack_test.cpp
- test/unittests/validation_stack_type_test.cpp
> Validate block result types

- circle.yml
- lib/fizzy/parser.cpp
- test/unittests/validation_test.cpp
Type mismatch when constant expression uses `global.get` looks to be not covered by spec tests (passed tests don't change here when I disable it).
> Validate types of instructions in constant expressions

- test/unittests/api_test.cpp
Either coverage is wrong, or the explicit constructor is not called. With these tests we make sure that values are always correct even if in the case `Trap`/`Void` don't get assigned via the explicit constructor, but by setting the `trapped` variable. We can figure out the case with coverage later (cc @chfast).
> test: Add unit tests for ExecutionResult constructors

- circle.yml
- lib/fizzy/parser_expr.cpp
- test/unittests/validation_stack_test.cpp
> Validate missing else branch

- circle.yml
- lib/fizzy/parser_expr.cpp
- test/unittests/validation_stack_test.cpp
- test/unittests/validation_stack_type_test.cpp
Depends on #408 
Some of related spec tests were already passing by accident, because the tests are not great:
https://github.com/WebAssembly/spec/blob/636b862b9c8a25ad65fb240fefd673e7f23bcdd0/test/core/select.wast#L296-L307
```wat
(assert_invalid
(module (func $type-num-vs-num (select (i32.const 1) (i64.const 1) (i32.const 1))))
"type mismatch"
)
(assert_invalid
(module (func $type-num-vs-num (select (i32.const 1) (f32.const 1.0) (i32.const 1))))
"type mismatch"
)
(assert_invalid
(module (func $type-num-vs-num (select (i32.const 1) (f64.const 1.0) (i32.const 1))))
"type mismatch"
)
```
^ These were invalid but for the wrong reason - functions are void but have result of `select` on stack in the end.
https://github.com/WebAssembly/spec/blob/636b862b9c8a25ad65fb240fefd673e7f23bcdd0/test/cor …
> Validate types for select instruction

- lib/fizzy/execute.cpp
- lib/fizzy/parser_expr.cpp
- test/unittests/parser_expr_test.cpp
Get rid of duplicated arity in `br_table` immediates.
> Single arity immediate per br_table instruction

- lib/fizzy/CMakeLists.txt
- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- lib/fizzy/stack.hpp
- lib/fizzy/value.hpp
- test/spectests/spectests.cpp
- test/unittests/CMakeLists.txt
- test/unittests/api_test.cpp
- test/unittests/execute_call_test.cpp
- test/unittests/execute_control_test.cpp
- test/unittests/execute_test.cpp
- test/unittests/instantiate_test.cpp
- test/unittests/span_test.cpp
- test/unittests/value_test.cpp
- test/utils/asserts.cpp
- test/utils/execute_helpers.hpp
- test/utils/fizzy_engine.cpp
The `Value` is an union for now containing only `i64` value. Later to be extended with `f32`, `f64` and maybe `i32`.
I added implicit conversions from/to `uint64_t` to limit the number of required changes.
The conversion from `std::initializer_list<uint64_t>` not possible in a type safe manner. I guess we will need something like `template<typename T...> TypedArgs` to construct a container of `Value`s. This will also handle usage of different value types in execution invocation.
All will get more complicated if we want constructor from other types (e.g. `float`, `unsigned int`) as we will get ambiguities (e.g. `0` is of type `int` and will not know where to go).
> Introduce Value type for operands

- lib/fizzy/execute.cpp
- lib/fizzy/value.hpp
- test/unittests/value_test.cpp
- test/utils/fizzy_engine.cpp
Depends on https://github.com/wasmx/fizzy/pull/419
> Value type improvements

- circle.yml
- lib/fizzy/execute.cpp
- lib/fizzy/parser_expr.cpp
- lib/fizzy/value.hpp
- test/unittests/CMakeLists.txt
- test/unittests/execute_floating_point_test.cpp
- test/unittests/parser_expr_test.cpp
- test/unittests/value_test.cpp
A symbolic milestone starting floating point support implementation.
> Implement floating point const and add

- test/smoketests/spectests/CMakeLists.txt
- test/spectests/spectests.cpp
Closes #450 
Current output without skipped:
```
> bin/fizzy-spectests ~/dev/wasm-spec/test/core/json/float_memory/
Running tests from /home/andrei/dev/wasm-spec/test/core/json/float_memory/float_memory.json
..s..ssFs..s..s..s..ssFs..s..s..s..ssFs..s..s..s..ssFs..s..s..s..ssFs..s..s..s..ssFs..s..s
Line 21: assert_return FAILED Incorrect returned value. Expected: 2141192192 (0x7fa00000) Actual: 0 (0x0)
Line 46: assert_return FAILED Incorrect returned value. Expected: 9219994337134247936 (0x7ff4000000000000) Actual: 0 (0x0)
Line 73: assert_return FAILED Incorrect returned value. Expected: 2141192192 (0x7fa00000) Actual: 0 (0x0)
Line 98: assert_return FAILED Incorrect returned value. Expected: 9219994337134247936 (0x7ff4000000000000) Actual: 0 (0x0)
Line 125: assert_return FAILED Incorrect …
```
> test: Improve spectest runner output

- circle.yml
- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- lib/fizzy/parser.cpp
- lib/fizzy/parser.hpp
- lib/fizzy/parser_expr.cpp
- lib/fizzy/types.hpp
- test/smoketests/spectests/CMakeLists.txt
- test/unittests/api_test.cpp
- test/unittests/execute_test.cpp
- test/unittests/instantiate_test.cpp
- test/unittests/parser_test.cpp
> Support floating point globals

- lib/fizzy/value.hpp
This checks if the floating point types used to implement `f32` and `f64` Wasm types are compliant with IEEE 754.
The CMake check is rather difficult to do. We would need to check if a test program compiles.
> Check floats compliance with IEEE 754

- lib/fizzy/execute.cpp
This should have been done in #423.
Depends on #446.
> Replace static_casts with Value::as<>

- test/unittests/CMakeLists.txt
- test/unittests/floating_point_utils_test.cpp
- test/utils/CMakeLists.txt
- test/utils/asserts.hpp
- test/utils/floating_point_utils.hpp
These are helpers mostly to inspect and build NaN "values". Wasm has concepts of canonical and arithmetic NaNs, which are not present in C/C++.
Some future usage examples:
- https://github.com/wasmx/fizzy/pull/457/files#diff-5c88f1e384667cb0ce959addfcea39e3R101-R127
- https://github.com/wasmx/fizzy/pull/458/files#diff-5c88f1e384667cb0ce959addfcea39e3R166-R183
> test: Add floating-point utils

- circle.yml
- lib/fizzy/CMakeLists.txt
- lib/fizzy/execute.cpp
- lib/fizzy/trunc_boundaries.hpp
- test/unittests/execute_floating_point_test.cpp
The operator from the wasm spec is partial, i.e. it has some undefined results.
But, the execution spec requires to trap on operator's undefined result.
> Implement float->int trunc instructions

- lib/fizzy/stack.hpp
cppcheck complains that the assertions which use `size()` could have side-effects because `size()` is not marked const -- I agree with that, but not sure if this has caused any downside.
> Mark size() const in OperandStack

- circle.yml
- lib/fizzy/execute.cpp
- test/unittests/execute_floating_point_test.cpp
Depends on #448.
Need to be cleaned up and unit tests.
> Implement f32/f64 comparison operators

- test/unittests/execute_floating_point_test.cpp
- test/unittests/floating_point_utils_test.cpp
It adds/fixes some testing helpers for floating point instructions.
Then it adds wasm spec-driver tests for `fadd`, i.e. it adds checks for these points from the definition:
> test: Add proper f{32,64}_add tests

- circle.yml
- lib/fizzy/execute.cpp
- test/unittests/execute_floating_point_test.cpp
Here situation is simple - we convert an integer to the closer floating point value. No special cases as range of `f32` is greater than `i64`.
> Implement int->float convert instructions

- circle.yml
- lib/fizzy/execute.cpp
- test/unittests/execute_floating_point_test.cpp
This is rather straight forward as conversion `f32` to `f64` is lossless. The only fancy checks are for `NaN` values. Canonical NaN must be converted to canonical one, and any other NaN must be converted to any arithmetic NaN.
https://webassembly.github.io/spec/core/exec/numerics.html#op-promote
> Implement f64.promote_f32 instruction

- circle.yml
- lib/fizzy/execute.cpp
- test/unittests/execute_floating_point_test.cpp
> Implement f{32,64}.abs instructions

- circle.yml
- lib/fizzy/execute.cpp
- test/unittests/execute_floating_point_test.cpp
> Implement f{32,64}.div instructions

- circle.yml
- lib/fizzy/execute.cpp
- test/unittests/execute_floating_point_test.cpp
> Implement f{32,64}.neg instructions

- circle.yml
- lib/fizzy/execute.cpp
- test/unittests/execute_floating_point_test.cpp
> Implement {f32,f64}.sqrt instructions

- circle.yml
- lib/fizzy/execute.cpp
- test/unittests/execute_floating_point_test.cpp
> Implement f{32,64}.copysign instructions

- test/unittests/execute_floating_point_test.cpp
Add missing checks for signaling (not arithmetic) NaNs.
https://webassembly.github.io/spec/core/exec/numerics.html#nan-propagation
> test: Check signaling NaN handling in binops

- circle.yml
- lib/fizzy/execute.cpp
- test/unittests/execute_floating_point_test.cpp
> Implement f{32,64}.{min,max} instructions

- circle.yml
- lib/fizzy/execute.cpp
- test/unittests/execute_floating_point_test.cpp
> Implement f{32,64}.mul instructions

- lib/fizzy/execute.cpp
- test/unittests/execute_floating_point_test.cpp
> Implement f32.demote_f64 instruction

- circle.yml
- lib/fizzy/execute.cpp
- test/unittests/execute_floating_point_test.cpp
> Implement reinterpret instructions

- circle.yml
- lib/fizzy/execute.cpp
- test/unittests/execute_floating_point_test.cpp
> Implement f{32,64}.sub instructions

- circle.yml
> ci: don't run fizzy-spectests --skip-validation

- circle.yml
- test/unittests/validation_test.cpp
On architectures with SSE4 and AVX, the floating point operations use different set of CPU instructions. Enabling native builds should tests these.
> ci: Add native builds

- circle.yml
- lib/fizzy/execute.cpp
- test/unittests/execute_floating_point_test.cpp
> Implement f{32,64}.{ceil,floor,trunc} instructions

- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- test/unittests/api_test.cpp
- test/unittests/execute_test.cpp
- test/unittests/instantiate_test.cpp
This fixes the disabled instantiation test.
Not covered by spec tests.
> Add value type to ExternalGlobal and check it at instantiate

- lib/fizzy/execute.cpp
This replaces usage of std::plus{} and others with simpler in-house
implementation. The difference is that the std:: versions are passing
arguments by reference. In GCC builds without optimization this may
cause the arguments to be swapped in commutative instructions. This is
at least annoyance for floating-point add which may produce different
NaN results if both inputs are NaNs. This is not a problem for Wasm
conformance, but prevents running exhaustive tests against software
floats implementations.
> Use simpler ops for binary instructions (fixes GCC issue)

- lib/fizzy/execute.cpp
This implementation does not need to modify rounding direction to work
correctly under any rounding direction.
> Change implementation of fnearest()

- lib/fizzy/stack.hpp
- test/unittests/stack_test.cpp
I started this to investigate "containter-overflow" issues reported by ASan in XCode 12.0 beta. This does not fix the issue, but at least I minimized the Stack interface and we don't use inheritance any more.
> Refactor Stack utility class

- circle.yml
Ordered some jobs like this:
The idea is to run more important jobs first, and in case of failures not to run others.
Besides, some other small improvements are included.
> CI improvements

- circle.yml
- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- lib/fizzy/limits.hpp
- test/spectests/spectests.cpp
- test/unittests/execute_test.cpp
- test/unittests/instantiate_test.cpp
> Make hard memory limit configurable

- circle.yml
This moves clang-tidy checking and C++20 build to "lint" job.
The `-Weverything` build will be added to "lint" too in #508.
> ci: Combine linter/style/tidy/portability checks

- lib/fizzy/CMakeLists.txt
- lib/fizzy/exceptions.cpp
- lib/fizzy/exceptions.hpp
- test/utils/wasm_engine.cpp
- test/utils/wasm_engine.hpp
This fixes -Wweak-vtable warnings, helpful for #508.
The effect in fizzy library is the following: vtables and typeinfos (**V**) are generates once in the `exceptions.cpp.o` instead of all files they were used. And the destructors are not `inline` any more (**W** -> **T**). This is good change as they are always cold.
I'm not convinced the impact is worth the trouble.
```diff
diff --git a/names.old b/names.fixed
index da7e6d25..47c47ba0 100644
--- a/names.old
+++ b/names.fixed
@@ -1,0 +2,20 @@
+exceptions.cpp.o:
+0000000000000060 T fizzy::parser_error::~parser_error()
+0000000000000000 T fizzy::parser_error::~parser_error()
+0000000000000000 T fizzy::parser_error::~parser_error()
+0000000000000090 T fizzy::validation_error::~validation_error()
+0000000000000020 T …
```
> Emit vtables once

- circle.yml
> ci: Use older clang-10 image for the coverage job

- circle.yml
I'd like to switch to using GCC for line-based coverage. The Clang source-based coverage will stay but will not be used on codecov.
There are two issues with Clang: it has some bugs (e.g. https://codecov.io/gh/wasmx/fizzy/src/3b19fb019b2d204ebe4cb7256d0cfb5db318b78e/lib/fizzy/parser.cpp#L155) and in the source-based coverage to line-based coverage conversion the comments are also marked as executed. The later screws the line count stats.
The plan is to prepare LCOV summary of the coverage on CI and only upload this single file (similarly to what we currently do with Clang).
> ci: Coverage with GCC

- test/smoketests/spectests/CMakeLists.txt
- test/spectests/spectests.cpp
> test: support running single file in fizzy-spectests

- circle.yml
- test/spectests/README.md
- wat2wasm4cpp.py
Adds simple script to convert WAST tests to JSON on CI instead of
relaying on JSON files being available in the wasm-spec repo.
> CI: Convert WAST test to JSON

- lib/fizzy/execute.cpp
> Simplify trap handling

- lib/fizzy/CMakeLists.txt
- lib/fizzy/cxx20/bit.hpp
- test/unittests/CMakeLists.txt
- test/unittests/bit_cast_test.cpp
- test/utils/floating_point_utils.hpp
Improve the bit_cast implementation to be as close as the C++20 spec.
Move it to lib/fizzy/cxx20/bit.hpp to match the <bit> header in C++20
and be available in the fizzy library.
> Improve and expose bit_cast implementation

- lib/fizzy/parser.cpp
- lib/fizzy/parser.hpp
- lib/fizzy/utf8.cpp
- test/unittests/parser_expr_test.cpp
- test/unittests/parser_test.cpp
- test/unittests/utf8_test.cpp
The previous pattern `pos + size < end` was incorrect leading to
possible undefined behavior and potential addition overflow allowing
the check bypass. The correct check is to compute the remaining size
and compare with the declared size. This way invalid pointer comparison
is replaced with correct pointer subtraction (pos and end are from the
same memory buffer) and integer comparison: `(end - pos) < size`.
This will be additionally check with extended ASan options in #469.
> Fix bounds checking pattern in parser

- lib/fizzy/execute.cpp
- lib/fizzy/stack.hpp
- test/unittests/span_test.cpp
- test/unittests/stack_test.cpp
This move memory management of args and locals to OperandStack where
space for all can be allocated in single go.
> Allocate space for locals together with stack

- circle.yml
- cmake/apply_patches.sh
- test/ci-benchmark.sh
Uses https://github.com/koalaman/shellcheck.
Should consider just installing shellcheck and not using the orb.
> Run shellcheck

- cmake/ProjectWabt.cmake
- test/utils/wabt_engine.cpp
For reference, here's PR intoducing new API: https://github.com/WebAssembly/wabt/pull/1330
> Upgrade WABT to 1.0.19

- lib/fizzy/CMakeLists.txt
- test/CMakeLists.txt
- test/bench/CMakeLists.txt
- test/bench_internal/CMakeLists.txt
- test/fuzzer/CMakeLists.txt
- test/spectests/CMakeLists.txt
- test/unittests/CMakeLists.txt
- test/utils/CMakeLists.txt
The fizzy::fizzy-internal links fizzy::fizzy library with access to internal headers. Do not include the directory with internal headers directly in test tools.
The tendency should be to migrate from using `fizzy::fizzy-internal` to `fizzy::fizzy` as we get more public API. Ideally, in the end only `fizzy-unittests` should be using `fizzy::fizzy-internal`.
Dependencies are getting messy.
> cmake: Add fizzy::fizzy-internal INTERFACE library

- .bumpversion.cfg
- .gitignore
- Cargo.toml
- bindings/rust/.gitignore
- bindings/rust/Cargo.toml
- bindings/rust/build.rs
- bindings/rust/src/lib.rs
- bindings/rust/src/sys.rs
- circle.yml
Depends on #530. Depends on #533.
> Rust bindings (validate only)

- lib/fizzy/execute.cpp
> Mark instruction helpers appropriately as constexpr

- test/benchmarks/ecpairing/.gitignore
- test/benchmarks/ecpairing/Cargo.toml
This was broken by #538 introducing the workspace.
> benchmarks: allow compiling ecpairing

- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- lib/fizzy/instantiate.cpp
- lib/fizzy/stack.hpp
- test/spectests/spectests.cpp
- test/testfloat/testfloat.cpp
- test/unittests/api_test.cpp
- test/unittests/execute_call_test.cpp
- test/unittests/execute_floating_point_test.cpp
- test/unittests/execute_test.cpp
- test/unittests/span_test.cpp
- test/unittests/stack_test.cpp
- test/utils/fizzy_engine.cpp
Part of #526 and #563.
Pass arguments to `execute()` as `const Value*`, without providing information about number of arguments. Previously arguments were passed as `span<const Value>`.
Also "host function" may be changed accordingly in following PR.
Some parts may be committed separately: 2 first commits, the `{Value(0)}` change in unit tests.
> Pass arguments as const Value*

- lib/fizzy/execute.cpp
This fixes logical error in `invoke_function()` implementation. The call arguments are now dropped from the stack after the call returns.
Performance difference is not significant.
```
fizzy/execute/blake2b/512_bytes_rounds_1_mean                     -0.0056         -0.0056            77            77            77            77
fizzy/execute/blake2b/512_bytes_rounds_16_mean                    -0.0105         -0.0105          1173          1160          1173          1160
fizzy/execute/ecpairing/onepoint_mean                             +0.0026         +0.0026        389544        390546        389548        390550
fizzy/execute/keccak256/512_bytes_rounds_1_mean                   +0.0067         +0.0067            93            94            93            94 …
```
> Fix invoke: drop args after the call

- test/utils/fizzy_engine.cpp
Clang 10 build with LTO
```
fizzy/instantiate/blake2b_mean                                     -0.0239         -0.0245            54            53            54            52
fizzy/instantiate/ecpairing_mean                                   -0.0485         -0.0403          2838          2701          2839          2724
fizzy/instantiate/keccak256_mean                                   -0.0375         -0.0315            94            90            94            91
fizzy/instantiate/memset_mean                                      -0.0617         -0.0592            18            17            18            17
fizzy/instantiate/mul256_opt0_mean                                 -0.0645         -0.0613            22            20            22            20
fizzy/instantiate/ramanujan_pi_mean …
```
> bench: move module and imports in FizzyEngine::instantiate

- circle.yml
`cargo build` will build Fizzy in Debug profile, while `cargo build --release` will do with Release in cmake, see https://docs.rs/cmake/0.1.44/cmake/struct.Config.html#method.profile. The more specific translation rules can be seen in https://docs.rs/cmake/0.1.44/src/cmake/lib.rs.html#553-558 (it can use `Release`, `RelWithDebInfo`, `MinSizeRel` depending on settings).
We could also decide to force Release mode if we want.
Furthermore it seems PIC is used in both modes, we may want to investigate this (see https://docs.rs/cmake/0.1.44/cmake/struct.Config.html#method.pic).
> ci: run Rust build in release mode too

- lib/fizzy/execute.cpp
Closes #540.
I created optimized first single case of issue #540 to be sure that i understood a problem.
> Optimize fabs, fneg, fcopysign

- CMakeLists.txt
- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- lib/fizzy/instantiate.cpp
- lib/fizzy/instantiate.hpp
- lib/fizzy/parser.cpp
- lib/fizzy/parser.hpp
- test/spectests/spectests.cpp
- test/unittests/api_test.cpp
- test/unittests/end_to_end_test.cpp
- test/unittests/execute_call_test.cpp
- test/unittests/execute_control_test.cpp
- test/unittests/execute_floating_point_test.cpp
- test/unittests/execute_numeric_test.cpp
- test/unittests/execute_test.cpp
- test/unittests/instantiate_test.cpp
- test/unittests/module_test.cpp
- test/unittests/parser_expr_test.cpp
- test/unittests/parser_test.cpp
- test/unittests/validation_stack_test.cpp
- test/utils/CMakeLists.txt
- test/utils/execute_helpers.hpp
- test/utils/fizzy_engine.cpp
- test/utils/instantiate_helpers.hpp
- tools/wasi/wasi.cpp
This will simplify C API implementation part, allowing to handle modules and instances in the same manner.
> refactor: Allocate module dynamically

- circle.yml
- include/fizzy/fizzy.h
- lib/fizzy/capi.cpp
- test/unittests/capi_test.cpp
Alternative to #533 based on #575
> C API execute with dynamically allocated module

- CMakeLists.txt
- circle.yml
- cmake/ProjectWabt.cmake
- cmake/toolchains/libc++.cmake
- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- lib/fizzy/instantiate.cpp
- test/utils/leb128_encode.cpp
- test/utils/leb128_encode.hpp
- Adds support for building with libc++ on linux by using CMake toolchain file.
- Upgrades C++20 CI job to `clang-11, libc++-11` from `clang-10, libstdc++`.
- Fixes some new clang-tidy issues.
> Build with libc++, C++20

- lib/fizzy/cxx20/bit.hpp
- lib/fizzy/execute.cpp
- test/unittests/CMakeLists.txt
- test/unittests/cxx20_bit_test.cpp
- test/unittests/cxx20_span_test.cpp
> Use popcount from C++20 if available

- test/unittests/capi_test.cpp
This changes some `EXPECT_NE` to `ASSERT_NE` and resolves one TODO.
> C API tests cleanup

- include/fizzy/fizzy.h
- lib/fizzy/capi.cpp
- test/unittests/capi_test.cpp
Replaces https://github.com/wasmx/fizzy/pull/565
> C API instantiate with resolving imported functions

- lib/fizzy/cxx20/bit.hpp
- lib/fizzy/cxx20/span.hpp
See https://en.cppreference.com/w/cpp/utility/feature_test which sets `__cpp_lib_span` as an alias to `201902L`, while we were testing for `201703L`.
> Use proper feature test for C++20 std::span

- lib/fizzy/CMakeLists.txt
- lib/fizzy/asserts.cpp
- lib/fizzy/asserts.hpp
- lib/fizzy/execute.cpp
- lib/fizzy/parser.cpp
- test/unittests/CMakeLists.txt
- test/unittests/asserts_test.cpp
- test/unittests/execute_death_test.cpp
Add macro FIZZY_UNREACHABLE to mark unreachable code.
It fails a standard assert in build with asserts enabled.
It fails in UBSan.
It is an optimization hint for optimized builds.
Replaces `assert(false` with `FIZZY_UNREACHABLE`.
Introduces "death tests". They are very expensive (single death test runs longer than all execution tests), so limited to single case.
We cannot use death tests to reach the unreachable code in parser because parsing and validation is done in single go and there is no way to inject malformed module to verification procedure.
> Introduce UNREACHABLE macro

- test/unittests/parser_expr_test.cpp
- test/unittests/parser_test.cpp
New checks are more type change tolerant what allows changing the `.instructions` type later.
> test: Use ElementsAre() to check arrays of instructions

- lib/fizzy/execute.cpp
- lib/fizzy/parser_expr.cpp
- lib/fizzy/types.hpp
- test/unittests/execute_death_test.cpp
- test/unittests/execute_numeric_test.cpp
- test/unittests/execute_test.cpp
- test/utils/asserts.hpp
This allows to move immediate values to the same array later. That will increase overall performance.
> Convert instructions to vector<uint8_t>

- circle.yml
The env var CMAKE_BUILD_PARALLEL_LEVEL sets the parallel level of `cmake --build`.
This default value 8 can be overwritten by setting `CMAKE_BUILD_PARALLEL_LEVEL` at job level. This is done for `sanitizers-gcc` to set value 6.
> ci: Use CMAKE_BUILD_PARALLEL_LEVEL with 8 by default

- CMakeLists.txt
- circle.yml
- cmake/ProjectWabt.cmake
- ci: Use libc++ for sanitizers-clang job
This should enable container-overflow checks.
- cmake: Drop _GLIBCXX_SANITIZE_VECTOR instrumentation
This conflicts with pointer-subtract and pointer-compare ASAn checks. Container-overflow checks are performed by Clang ASan + libc++ builds.
> ci: Use libc++ for sanitizers-clang job

- lib/fizzy/execute.cpp
- lib/fizzy/instantiate.cpp
- lib/fizzy/instantiate.hpp
- test/unittests/api_test.cpp
- test/unittests/execute_call_test.cpp
- test/unittests/instantiate_test.cpp
> Refactor table and simplify calls

- circle.yml
At this stage, it has 5 spectests failures.
- FIXED: One of the tests that we failed (and reported as invalid), was deleted https://github.com/WebAssembly/spec/pull/1205
- 4 tests are going to be fixed by #546.
- FIXED: 1 failure old failure is "validation-error-before-decoding-error", and it fixed upstream by https://github.com/WebAssembly/spec/pull/1261.
- FIXED: 2 new failures in `func.wast`, the reason is wast2json generates incorrect local index in the module. It still happens in wabt 1.0.19, but is fixed on master. Related issues/PRs:
- https://github.com/WebAssembly/wabt/issues/1551
- https://github.com/WebAssembly/spec/pull/1213
- https://github.com/WebAssembly/wabt/pull/1466
- https://github.com/WebAssembly/wabt/pull/1494
TODO:
> Update spectests with backports

- circle.yml
- lib/fizzy/parser.cpp
- test/unittests/parser_test.cpp
Depends on #534. 
Fizzy fix for the proposed spectests: https://github.com/WebAssembly/spec/pull/1249.
Element section tests correction: https://github.com/WebAssembly/spec/pull/1251.
I also changed the error message.
> Use validation error message "unknown memory N" for both N != 0 and data segments without any memory in the module. Inspired by messages in wasm reference interpreter.
> Change "unexpected memidx" to validation error

- lib/fizzy/value.hpp
- test/unittests/execute_numeric_test.cpp
> Add assert to as<int32_t>() for dirty higher bits.

- test/unittests/execute_call_test.cpp
> test: Add more tests of calls to functions without results

- include/fizzy/fizzy.h
- lib/fizzy/capi.cpp
- test/unittests/capi_test.cpp
- test/utils/fizzy_c_engine.cpp
I'm not completely sure it's a good idea to include this, because complications with context can be confusing, but the motivation is 
1. to make it simpler to import exported function into another module - see `capi.imported_function_from_anothe_module` test change.
2. symmetry with C++ API `fizzy::find_exported_*` functions.
> capi: find_exported_function

- circle.yml
- codecov.yml
- Upload coverage from internal tests with "unittests" flag.
- Upload coverage from spectests with "spectests" flag.
- Show the coverage for each flag in the Codecov Report comment.
See #644.
> CI: Coverage flags

- bindings/rust/Cargo.toml
- bindings/rust/src/lib.rs
> Rust bindings (unsafe execution)

- lib/fizzy/parser.cpp
- lib/fizzy/types.hpp
> Move code_view from types.hpp to parser.cpp

- test/unittests/capi_test.cpp
- test/unittests/execute_control_test.cpp
- test/unittests/instantiate_test.cpp
Replace host functions not being executed with null pointers or common functions. Code coverage is happy.
> test: Avoid dead host functions

- test/smoketests/spectests/CMakeLists.txt
- test/spectests/spectests.cpp
This can be helpful, when you'd like to check whether the invalid case fails for the right reason.
(It is displayed only with `--show-passed` option)
> test: Log error message for spectests expecting a failure

- test/bench/CMakeLists.txt
- test/spectests/CMakeLists.txt
- test/utils/CMakeLists.txt
- tools/wasi/CMakeLists.txt
These are not needed, because `fizzy` library includes it, as pointed out in https://github.com/wasmx/fizzy/pull/329#discussion_r461691537
> cmake: Remove redundant target_compile_features(... cxx_std_17)

- test/unittests/capi_test.cpp
This test was added before imporing memory was supported in C API. Now I remembered that it should actually test something.
> test: improve capi.imported_memory_access test

- lib/fizzy/execute.cpp
- lib/fizzy/limits.hpp
- test/unittests/execute_call_test.cpp
Previously there were 2049 number of recursive calls allowed (depth levels from 0 to 2048). With this change the number is reduced to 2048 (depth levels from 0 to 2047).
> Correct max call depth

- circle.yml
- test/unittests/CMakeLists.txt
- test/unittests/api_test.cpp
- test/unittests/execute_control_test.cpp
- test/unittests/execute_floating_point_test.cpp
- test/unittests/execute_invalid_test.cpp
- test/unittests/execute_numeric_test.cpp
- test/unittests/execute_test.cpp
- test/unittests/typed_value_test.cpp
- test/utils/execute_helpers.hpp
- test/utils/typed_value.hpp
After previously introducing `TypedValue` in #658, this PR adds type checking for execution arguments in unit tests. The type checking is done in `fizzy::test::execute()` so can be bypassed by using `fizzy::execute()` directly. Still most of the tests uses the former.
Later we will add type checking to the execution result and the `Result()` matcher. We will be also able to see the type-checking bypassing cases and correct these if needed.
> test: Check the types of execution arguments

- lib/fizzy/capi.cpp
- lib/fizzy/cxx20/span.hpp
- lib/fizzy/instantiate.cpp
- lib/fizzy/instantiate.hpp
- test/unittests/api_test.cpp
- test/unittests/cxx20_span_test.cpp
- test/unittests/instantiate_test.cpp
This allows to avoid extra vector allocation when going from C `FizzyExternalFunction` to C++ `fizzy::ExternalFunction` and also when C++ API returns from `find_exported_function()`.
Also I it helps with `std::function` refactoring in #643 
The downside is that user has to ensure that arrays pointed to by spans live long enough (usually these arrays are in `Instance`, and you need this `Instance` to run `ExternalFunction` anyway).
This leaves `ImportedFunction` still using `vector<ValType>` for input types, I think it's convenient to leave it like this, otherwise it wouldn't be possible to pass input types as inline initializer list like this:
```cpp
auto imports = fizzy::resolve_imported_functions(
*module, {
{"env", "adler32", {fizzy::ValType::i32, fizzy::ValType::i32}, …
```
> refactor: Use span instead of vectors in ExternalFunction

- test/unittests/api_test.cpp
- test/unittests/execute_call_test.cpp
- test/unittests/execute_control_test.cpp
- test/unittests/execute_numeric_test.cpp
- test/unittests/execute_test.cpp
- test/unittests/test_utils_test.cpp
- test/utils/asserts.cpp
- test/utils/asserts.hpp
- test/utils/execute_helpers.hpp
- test/utils/typed_value.hpp
> test: Add TypedExecutionResult, check result type

- include/fizzy/fizzy.h
- lib/fizzy/capi.cpp
- test/unittests/capi_test.cpp
> capi: has_memory and has_table checks

- include/fizzy/fizzy.h
- lib/fizzy/execute.cpp
- lib/fizzy/instantiate.cpp
- lib/fizzy/stack.hpp
- lib/fizzy/value.hpp
- test/testfloat/testfloat.cpp
- test/unittests/api_test.cpp
- test/unittests/capi_test.cpp
- test/unittests/cxx20_span_test.cpp
- test/unittests/execute_numeric_test.cpp
- test/unittests/execute_test.cpp
- test/unittests/stack_test.cpp
- test/unittests/test_utils_test.cpp
- test/unittests/typed_value_test.cpp
- test/unittests/value_test.cpp
- test/utils/asserts.hpp
- test/utils/fizzy_c_engine.cpp
- test/utils/fizzy_engine.cpp
Problems this introduces
- `stack.top() = 0` only zeros the `.i32` now.
- `FizzyValue{1}` only inits the `.i32` part. This is excessively used in C API tests. And cannot be disabled. In C++20 you can do `FizzyValue{.i64 = 1}`.
> Add uint32_t i32 field to Value union

- test/unittests/api_test.cpp
- test/unittests/execute_call_test.cpp
- test/unittests/execute_test.cpp
- test/unittests/instantiate_test.cpp
- test/unittests/parser_test.cpp
- test/utils/asserts.hpp
> test: Drop as_uint32()

- lib/fizzy/stack.hpp
- test/unittests/stack_test.cpp
Fixes https://github.com/wasmx/fizzy/issues/583.
> Adjust OperandStack allocation size when no locals

- test/spectests/spectests.cpp
Spectest predefined module now has a proper spec: https://github.com/WebAssembly/spec/pull/1280
There were a couple of members missing which are not used anyway, so this change is only cosmetic.
> test: Update spectest module definition

- README.md
- cmake/ProjectUVWASI.cmake
- tools/wasi/wasi.cpp
uvwasi was transferred into the Node.js GitHub org.
This commit updates the repository's link.
> Update uvwasi repository address

- include/fizzy/fizzy.h
- lib/fizzy/capi.cpp
- test/unittests/capi_test.cpp
> capi: Import inspection functions

- lib/fizzy/instantiate.cpp
- lib/fizzy/instantiate.hpp
- test/unittests/api_test.cpp
~~This extends `resolve_imported_functions` function into supporting all kinds of imports.~~
I decided to leave here only support for imported globals. Resolving imported table and memory doesn't seem very useful, becasue there's always at most one of each. I suggest to postpone that till we see there's real need to resolve them.
C API part will be in another PR.
> api: resolving imported globals

- lib/fizzy/capi.cpp
One commit from #660 and one commit from #694
> capi: Random minor simplifications

- include/fizzy/fizzy.h
- lib/fizzy/capi.cpp
- test/unittests/capi_test.cpp
> capi: resolve imported globals

- bindings/rust/src/lib.rs
> rust: use i32 type in Value

- circle.yml
Trying to fix random lint job failures.
> ci: Don't run doxygen installation in background

- circle.yml
- wat2wasm4cpp.py
- wat2wasm4tests.py
Closes #593.
I used `rustfmt` becaust it takes a single file as argument.
However, it doesn't seem much useful, e.g. long hex strings are not broken down (this option is unstable and off by default
https://rust-lang.github.io/rustfmt/?version=v1.4.33&search=#format_strings
https://github.com/rust-lang/rustfmt/issues/3353)
> Support Rust files in wat2wasm4cpp.py script

- test/unittests/test_utils_test.cpp
This improves coverage in `asserts.hpp`
> test: Unit test for CResult matcher

- bindings/rust/src/lib.rs
> rust: add typed value and execution result

- test/testfloat/CMakeLists.txt
- test/testfloat/testfloat.cpp
Change the testfloat option name to be more specific what it does:
ignores specific NaN payload values, but NaN categories are still
checked.
> testfloat: Rename -ignoreNaNs to -ignore_nan_payloads

- test/testfloat/CMakeLists.txt
For FP arithmetic function NaN payloads are now ignored:
- different payloads are produced on arm64 than in SoftFloat,
- add & mul are considered commutative therefore operands may be swapped
(we have evidences of compilers doing this when optimizing) -
what produces "unexpected" NaN payload.
> testfloat: Ignore NaN payloads for arith functions

- README.md
- bindings/rust/src/lib.rs
- circle.yml
This is what the documentation looks like:
> rust: add example code and mention in the readme

- cmake/Hunter/config.cmake
- cmake/Hunter/init.cmake
Required for #716 
Older version of nlohmann_json has some compilation errors when `<any>` is included, see https://github.com/wasmx/fizzy/pull/716#issuecomment-779365591 for links.
> Upgrade Hunter to get newer nlohmann_json

- circle.yml
This is to check new spec tests backported from wasm spec master.
Branch with new tests: https://github.com/wasmx/wasm-spec/pull/2
> ci: Update spectests branch

- test/utils/fizzy_engine.cpp
- test/utils/wasm_engine.hpp
Addressing https://github.com/wasmx/fizzy/pull/739#discussion_r582842022 .
> test: Refactor translate_signature in wasm_engine

- bindings/rust/src/lib.rs
This is the string version of #677.
> rust: return string as an error

- lib/fizzy/value.hpp
- test/unittests/value_test.cpp
This disables Value constructors for unsigned integers for types other
than uint32_t/uint64_t. This requires users to use these types.
This can cause portability issues on macOS/Linux if type like
unsigned long is used. This also helps in 32-bit port.
> Construct Value only from uint32_t/uint64_t

- lib/fizzy/parser.cpp
Fixes build issues on 32-bit architectures.
> parser: Fix types for out-of-bound checks

- CMakeLists.txt
- circle.yml
- test/smoketests/wasi/CMakeLists.txt
- test/unittests/CMakeLists.txt
- test/unittests/wasi_test.cpp
- tools/wasi/CMakeLists.txt
- tools/wasi/main.cpp
- tools/wasi/wasi.cpp
- tools/wasi/wasi.hpp
> WASI testing

- lib/fizzy/capi.cpp
- lib/fizzy/instantiate.cpp
- lib/fizzy/instantiate.hpp
- test/unittests/api_test.cpp
- test/unittests/execute_call_test.cpp
- test/unittests/execute_control_test.cpp
- test/unittests/execute_test.cpp
- test/unittests/instantiate_test.cpp
- test/utils/fizzy_engine.cpp
- tools/wasi/wasi.cpp
> refactor: ExecuteFunction without std::function

- cmake/CableBuildType.cmake
As the title states. If Fizzy is included into a project via `add_subdirectory()` the following error message appears:
```
CMake Error at ext/fizzy/cmake/CableBuildType.cmake:46 (message):
cable_set_build_type() must be used before project()
Call Stack (most recent call first):
ext/fizzy/CMakeLists.txt:27 (cable_set_build_type)
```
In almost all cases, `CMAKE_CURRENT_{SOURCE|BINARY|LIST}_DIR` should be used over the non-`CURRENT` versions for this reason.
> Fix cable CMake error message when built as a subdirectory

- bindings/rust/src/lib.rs
- include/fizzy/fizzy.h
- lib/fizzy/capi.cpp
- lib/fizzy/execute.hpp
- test/unittests/capi_test.cpp
- test/utils/fizzy_c_engine.cpp
In preparation for landing `ExecutionContext`, the default value for depth param is dropped in C++ and the param is completely removed from C and Rust (therefore C and Rust are not able to legally call wasm functions from host functions temporarily).
> Drop default depth param from execute()

- test/unittests/execute_call_depth_test.cpp
Depends on #757.
This removes the test cases where host functions dump the wasm call
depth. This is still possible (two cases doing that remain) but not
recommended implementation.
The remaining two cases should be cleaned up and moved to `execute_call_depth_test`.
> test: Do not bump depth in host functions

- lib/fizzy/instantiate.cpp
- test/unittests/instantiate_test.cpp
- This improves error message for the case when import's max is below min: `provided imported table doesn't fit provided limits` => `provided import's min limit is above import's max limit`.
- Also it will allow to simplify imported memory size checks in #755 (to leave only the check `memory.size() == min.limit` in instantiate).
> Add explicit check for imported limits validity

- include/fizzy/fizzy.h
- lib/fizzy/capi.cpp
- test/unittests/capi_test.cpp
- test/utils/fizzy_c_engine.cpp
- test/utils/fizzy_engine.cpp
Addresses https://github.com/wasmx/fizzy/pull/772#discussion_r603309139.
Depends on #776.
> capi: mark all external functions noexcept

- bindings/rust/integration-test/src/main.rs
- bindings/rust/src/lib.rs
> rust: support rich errors

- lib/fizzy/CMakeLists.txt
- lib/fizzy/execute.cpp
- lib/fizzy/execute.hpp
- lib/fizzy/execution_context.hpp
- test/unittests/execute_call_depth_test.cpp
Before #777  lands I propose to generalize `ExecutionContext`:
- move it to `execution_context.hpp`,
- rename `Guard` to something like `LocalContext`,
- rename `increment_call_depth()` to something like `create_local_context()`.
> Execution context generalization

- include/fizzy/fizzy.h
- lib/fizzy/capi.cpp
- test/unittests/capi_test.cpp
> capi: Use camelcase for FizzyErrorCode members

- include/fizzy/fizzy.h
Addresses comment https://github.com/wasmx/fizzy/pull/769#discussion_r605143971
> capi: Add a note about error code and returned value relation

- test/unittests/execute_floating_point_test.cpp
The i386 x87 FPU performs all arithmetic with 80-bit extended precision
by default and in the end rounds it to the required type. This causes
issues for f64 types because results may be different than when doing
computation with 64-bit precision. f32 is not affected.
These tests presents examples of results which are different in such
case.
> test: Add f64.{add,sub} off by one unit tests

- test/unittests/wasi_test.cpp
- tools/wasi/CMakeLists.txt
- tools/wasi/uvwasi.cpp
- tools/wasi/uvwasi.hpp
- tools/wasi/wasi.cpp
- tools/wasi/wasi.hpp
> wasi: Add UVWASI interface

- cmake/Hunter/config.cmake
- cmake/Hunter/init.cmake
Previous version of benchmark (1.5.0) does not build under GCC 11.
The 1.5.3 is the latest release.
> hunter: Upgrade benchmark to 1.5.3

- circle.yml
- cmake/ProjectUVWASI.cmake
- cmake/ProjectWabt.cmake
- cmake/ProjectWasm3.cmake
- cmake/toolchains/32bit.cmake
- test/testfloat/CMakeLists.txt
- test/unittests/execute_floating_point_test.cpp
- test/unittests/floating_point_utils_test.cpp
- test/utils/floating_point_utils.hpp
> Add 32-bit build

- lib/fizzy/cxx20/bit.hpp
- lib/fizzy/execute.cpp
- test/unittests/bitcount_test_cases.hpp
- test/unittests/cxx20_bit_test.cpp
- test/unittests/execute_numeric_test.cpp
> Use countl_zero/countr_zero from C++20 if available

- lib/fizzy/execute.cpp
Even if all you're doing with the resulting reference is deriving a pointer to one-past-the-end.
Or it might be UB. Unclear.
At least: according to [cplusplus.com](https://www.cplusplus.com/reference/vector/vector/operator[]/) calling operator[] on a vector with an out-of-range argument is UB.
UBSan does not report anything, however. Or rather: it reports UB if you form a reference to `v[v.size()]` for an empty vector `v`, but not for a nonempty vector `v`. Go figure.
Building with `-stdlib=libc++` and `-D_LIBCPP_DEBUG=1` produces a runtime error `_LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds` for empty or nonempty vectors.
In the C++ spec section 1.3.2 [dcl.ref] it says that "A reference shall be initialized to refer to a valid object". Furthermore table 88 defines …
> Indexing into a vector past its end is UB.

- test/spectests/spectests.cpp
- test/testfloat/testfloat.cpp
- test/unittests/execute_floating_point_conversion_test.cpp
- test/unittests/execute_floating_point_test.cpp
- test/unittests/execute_floating_point_test.hpp
- test/unittests/floating_point_utils_test.cpp
- test/unittests/test_utils_test.cpp
- test/utils/asserts.cpp
- test/utils/asserts.hpp
- test/utils/floating_point_utils.hpp
This enhance the FP utility type to be used in test cases and expected results in place of raw floating-point types. This gives better control of the floating-point binary representation and avoid places where some inplicit conversion may happen.
> test: Enhance FP utils and tests

- cmake/ProjectUVWASI.cmake
- tools/wasi/uvwasi.cpp
This allows removing two workarounds needed for earlier uvwasi versions.
> Upgrade uvwasi to 0.0.12

- bindings/rust/src/lib.rs
Depends on #783.
Based on #677.
> rust: Overhaul errors to use an enum

- circle.yml
> circleci: Disable spectests for arm64-native

- circle.yml
The spectests preparation requires pre-built WAST tools so do it once
per pipeline on x64 architecture. The test files are then available
in CircleCI workspace.
> ci: Separate spectests preparation

- bindings/rust/src/lib.rs
- include/fizzy/fizzy.h
- lib/fizzy/capi.cpp
- test/unittests/capi_execute_test.cpp
- test/unittests/capi_instantiate_test.cpp
- test/unittests/capi_test.cpp
- test/utils/fizzy_c_engine.cpp
> capi: Access to ExecutionContext members

- circle.yml
Fixes #727.
Proof of failure: https://app.circleci.com/pipelines/github/wasmx/fizzy/7058/workflows/c5870ebb-07e4-489c-9edb-ddf976503441/jobs/64657/parallel-runs/0/steps/0-106
> circleci: Add check for "cargo +nightly fmt"

- circle.yml
Simpler alternative to #750 
Branch with new tests: https://github.com/wasmx/wasm-spec/pull/4
> ci: Update spectests branch - skipping tests for post-1.0 features

- .bumpversion.cfg
Remove quotes for Cargo.toml fields
It seems that
1) with quotes it won't detect it
2) needs a `replace` field too as, while without quotes it detects it, it won't replace it
Inspired by https://github.com/ethereum/evmc which uses this configuration.
> Fix bumpversion.cfg
