wasmx/fizzy

lib/fizzy/leb128.hpp, test/unittests/leb128_test.cpp
https://webassembly.github.io/spec/core/binary/values.html#integers
https://en.wikipedia.org/wiki/LEB128
=> LEB128 decoder

lib/fizzy/CMakeLists.txt, lib/fizzy/leb128.hpp, lib/fizzy/parser.cpp, lib/fizzy/parser.hpp, lib/fizzy/types.hpp, test/unittests/CMakeLists.txt, test/unittests/parser_test.cpp, test/unittests/utils.cpp, test/unittests/utils.hpp
=> wasm binary parser

lib/fizzy/execute.cpp, lib/fizzy/parser_expr.cpp, lib/fizzy/types.hpp, test/unittests/execute_test.cpp
=> Implement i32.const and i64.const

lib/fizzy/execute.cpp, lib/fizzy/parser_expr.cpp, lib/fizzy/types.hpp, test/unittests/execute_test.cpp
=> Implement call

lib/fizzy/execute.cpp, lib/fizzy/parser.hpp, test/unittests/instantiate_test.cpp, test/unittests/parser_test.cpp
=> Enforce memory limits properly

lib/fizzy/execute.cpp, test/unittests/execute_control_test.cpp
=> Implement labels

lib/fizzy/execute.cpp, test/unittests/execute_control_test.cpp
=> Implement blocks with results (non-zero arity)

lib/fizzy/execute.cpp, lib/fizzy/parser.cpp, lib/fizzy/types.hpp, test/unittests/instantiate_test.cpp, test/unittests/parser_test.cpp
=> Implement support for Data section

test/unittests/end_to_end_test.cpp
=> Milestone 2

lib/fizzy/execute.cpp
Requested in https://github.com/wasmx/fizzy/pull/100#discussion_r371974350
=> Move memory-related helper functions to anonymous namespace at the top of execute.cpp

lib/fizzy/execute.cpp, lib/fizzy/parser_expr.cpp, lib/fizzy/types.hpp, test/unittests/execute_test.cpp
=> Implement call_indirect instruction

lib/fizzy/execute.cpp, test/unittests/instantiate_test.cpp
=> Implement initialization of element section offsets from global constant

lib/fizzy/execute.cpp, lib/fizzy/execute.hpp
=> Change instantiate() to take Module by value

lib/fizzy/execute.cpp, lib/fizzy/parser_expr.cpp
This should help with `if/else` implementation - allows inspecting what instruction has created a label.
=> Make LabelPosition a struct with instruction field

lib/fizzy/parser.cpp, test/unittests/parser_test.cpp
Depends on parsing imported tables https://github.com/wasmx/fizzy/pull/112
=> Validate number of imported memories and tables in parser

lib/fizzy/execute.cpp
=> Introduce alias for instance.memory in execute

test/bench/bench.cpp, test/utils/fizzy_engine.cpp, test/utils/wasm_engine.hpp
=> wasm_engine: replace FuncIdx with FuncRef

cmake/ProjectWasm3.cmake, test/bench/bench.cpp, test/utils/CMakeLists.txt, test/utils/wasm3_engine.cpp, test/utils/wasm_engine.hpp
=> Add wasm3 to fizzy-bench

lib/fizzy/exceptions.hpp, lib/fizzy/execute.hpp, lib/fizzy/leb128.hpp, lib/fizzy/parser.hpp, test/unittests/leb128_test.cpp
Follow up: https://github.com/wasmx/fizzy/pull/151#discussion_r377773462
=> Replace runtime_error with parser_error in leb128

test/spectests/spectests.cpp
Some `module` commands define a name for a module, for example in `elem.json`:
```json
{"type": "module", "line": 333, "name": "$module1", "filename": "elem.38.wasm"}, 
```
Then some invoke commands refer to this name:
```json
{"type": "assert_trap", "line": 353, "action": {"type": "invoke", "module": "$module1", "field": "call-7", "args": []}, "text": "uninitialized element", "expected": [{"type": "i32"}]}, 
```
For modules without a name this PR defines internally used name - this replaces previously used `optional<Instance>`.
This also prepares for implementing `register` command which will create a mapping between a module name as seen in imports and a module name from `module` command. This mapping then will be used to link imports/exports of several modules.
=> spectest: support invoke referring to module by name

lib/fizzy/parser.cpp, lib/fizzy/parser.hpp, lib/fizzy/parser_expr.cpp, test/unittests/parser_expr_test.cpp
=> Parse expr bounds checking

lib/fizzy/CMakeLists.txt, lib/fizzy/bytes.hpp, lib/fizzy/types.hpp, test/utils/fizzy_engine.cpp, test/utils/hex.hpp, test/utils/wasm3_engine.cpp, test/utils/wasm_engine.hpp
Fixes https://github.com/wasmx/fizzy/pull/192#discussion_r382022899
=> Move bytes/bytes_view definitions to bytes.hpp

test/unittests/parser_test.cpp
=> tests: add parser tests for empty sections

test/spectests/spectests.cpp
Fix to correctly parse and compare i32 signed values, similar to the fix in https://github.com/wasmx/fizzy/pull/205
Some tests were failing because of this https://github.com/wasmx/fizzy/pull/205#issuecomment-591490490
=> spectest: fix i32 arguments/results handling

test/bench/bench.cpp, test/bench_internal/parser_benchmarks.cpp
=> bench: Better unused variable supression

lib/fizzy/parser.cpp, test/unittests/parser_test.cpp
=> Do not allow wrongly ordered sections

test/unittests/parser_test.cpp
=> tests: generate floating point instructions properly

circle.yml, test/spectests/spectests.cpp, wat2wasm4cpp.py
Requires https://github.com/wasmx/fizzy/pull/135 and https://github.com/wasmx/fizzy/pull/170
=> spectest: hard-code "spectest" module

circle.yml, test/ci-benchmark.sh
1. New "benchmarking" workflow containing the "benchmark" job.
2. The "benchmarking" workflow does not run by default, but can be triggered via Circle CI API.
3. The script has been added that triggers the workflow.
=> CI: Manual benchmarking workflow

test/unittests/parser_expr_test.cpp, test/unittests/parser_test.cpp, test/utils/CMakeLists.txt, test/utils/leb128_encode.hpp, test/utils/wasm_binary.hpp
This is going to be reported as validation failure so fix it before #244.
=> test: Update tests to avoid stack underflow 

lib/fizzy/execute.cpp, lib/fizzy/execute.hpp, test/spectests/spectests.cpp, test/unittests/api_test.cpp, test/unittests/end_to_end_test.cpp, test/unittests/execute_call_test.cpp, test/unittests/execute_control_test.cpp, test/unittests/execute_test.cpp, test/unittests/instantiate_test.cpp, test/utils/fizzy_engine.cpp
Required for https://github.com/wasmx/fizzy/pull/246
=> Dynamically allocate Instance

test/unittests/execute_test.cpp
=> test: Rewrite store/load execution tests

lib/fizzy/execute.cpp
Not very beautiful, but this stack will go away Soon™ and this change separates it from operand stack `Stack<uint64_t>`.
=> execute: Replace runtime control stack implementation with std::stack

test/unittests/instantiate_test.cpp
Required for https://github.com/wasmx/fizzy/pull/268
=> test: convert imports-related instantiation tests to wat2wasm

test/unittests/CMakeLists.txt, test/unittests/execute_test.cpp, test/utils/asserts.hpp
=> test: introduce EXPECT_THAT helper

test/unittests/api_test.cpp, test/unittests/end_to_end_test.cpp, test/unittests/execute_call_test.cpp, test/unittests/execute_control_test.cpp, test/unittests/execute_numeric_test.cpp, test/unittests/execute_test.cpp, test/unittests/parser_expr_test.cpp, test/utils/asserts.hpp
All of them have been changed now. Reduction of 600 lines.
=> test: massive overhaul to use EXPECT_THAT

lib/fizzy/parser.cpp, lib/fizzy/parser.hpp, lib/fizzy/parser_expr.cpp
=> Use parse<uint8_t> in multiple places and rename it to parse_byte

test/bench/bench.cpp
Adds validate_benchmark_case() to perform test execution. This code is
extracted because in this version of libbenchmark it is expected to
always reach the main benchmarking loop, even if SkipWithError() has
been used.
=> bench: Refactor execution preparation code

circle.yml, lib/fizzy/instructions.cpp, lib/fizzy/module.hpp, lib/fizzy/parser_expr.cpp, test/unittests/parser_expr_test.cpp, test/unittests/parser_test.cpp, test/unittests/validation_stack_test.cpp, test/unittests/validation_test.cpp
=> Call instructions stack validation

lib/fizzy/execute.cpp, lib/fizzy/parser.cpp
We use more TODOs more often and actually these cases were not bugs, just missing features.
=> Change some FIXMEs to TODOs

cmake/ProjectWasm3.cmake, cmake/apply_patches.sh, cmake/wasm3_01_extapi.patch, cmake/wasm3_02_portable.patch
~~Need to compare benchmarks pre and post this change.~~
Should rebase my fork off wasm3 0.4.7 so we have a stable release we are benchmarking against.
=> cmake: update wasm3 to 0.4.7 and apply patches locally

lib/fizzy/parser_expr.cpp
Preparation for #312. 
Just reorders cases in instruction parser loop to have control instructions together and ordered by binary encoding.
=> refactor: Group control instructions together in expression parser loop

lib/fizzy/execute.cpp, lib/fizzy/stack.hpp, test/unittests/stack_test.cpp
Recreation of #264, pulled out of #247.
=> Refactor Stack interface to be similar to OperandStack

circle.yml, lib/fizzy/parser.cpp, test/unittests/parser_test.cpp
This was previously a parser error.
=> Raise validation error on element provided but missing table section

lib/fizzy/module.hpp, lib/fizzy/parser.cpp
=> Add module helpers

test/smoketests/spectests/CMakeLists.txt
=> test: add more test cases for fizzy-spectests CLI

lib/fizzy/execute.cpp
=> Mark load/store memory as noexcept

lib/fizzy/parser_expr.cpp
Required for type validation, pulled out from #385
=> parser: save block type

lib/fizzy/parser.cpp, lib/fizzy/parser_expr.cpp
Missed in or follow-up of #206.
=> Use parse_byte in parser where appropriate

circle.yml
Fixes https://github.com/wasmx/fizzy/pull/433#discussion_r458262639
=> ci: update wabt

circle.yml
=> ci: run full spec test suite

lib/fizzy/execute.cpp, lib/fizzy/value.hpp, test/unittests/execute_numeric_test.cpp, test/unittests/value_test.cpp
=> Remove dirty stack cases

test/unittests/execute_numeric_test.cpp
=> test: Add additional i64_extend_i32_u test

circle.yml
=> CI: Improve spectests coverage report

test/unittests/leb128_test.cpp
I reworked the arrays of test cases for LEB128 to use static initialization. This helps with reporting code coverage.
=> test: Rework LEB128 test cases

test/unittests/capi_test.cpp
=> test: Improve capi.resolve_instantiate_functions test

circle.yml, cmake/toolchains/arm64-linux.cmake, test/testfloat/CMakeLists.txt
=> Build and testing for arm64

lib/fizzy/execute.cpp
=> memory.grow 32-bit fix

circle.yml
=> ci: Reenable disabled sanitizer options in sanitizers-gcc

lib/fizzy/execute.cpp, lib/fizzy/instructions.hpp, test/unittests/execute_test.cpp
Addresses https://github.com/wasmx/fizzy/issues/621#issuecomment-1298594860.
=> Support metering cost for memory pages
